include:
  - board: nice_nano_v2  # 👈 v0.3에서는 v2가 맞습니다.
    shield: corne_left
    
  - board: nice_nano_v2
    shield: corne_right
    
  - board: seeeduino_xiao_ble
    shield: dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_BLE=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2 -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_SERIAL=y -DCONFIG_CONSOLE=y -DCONFIG_UART_CONSOLE=y -DCONFIG_BT_CTLR_TX_PWR_PLUS_8=y
    artifact-name: dongle

  - board: nice_nano_v2
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
